app/blueprints/pokemon/models.py
from datetime import datetime
from app import db


class CollectedPokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    pokemon = db.Column(db.String(40))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

app/blueprints/pokemon/__init__.py
from flask import Blueprint

bp = Blueprint('poke', __name__, url_prefix='/poke')

from . import routes, models

app/blueprints/pokemon/routes.py
from . import bp as poke_bp
from flask import render_template, redirect, url_for
import requests
from app.forms import PokemonForm
from flask_login import login_required, current_user
from app.blueprints.user.models import User
from .models import CollectedPokemon


user_input = []
@poke_bp.route('/pokemon', methods=['GET', 'POST'])
@login_required
def pick_pokemon():
    poke = PokemonForm()
    pokemon = poke.pokemon.data
    if poke.validate_on_submit():
        user_input.clear() 
        req = requests.get(f'https://pokeapi.co/api/v2/pokemon/{pokemon}')
        data = req.json()
        
        user_input.append(data['name'])
        
        abilities = data['abilities']
        abilities = list(map(lambda x: x['ability']['name'], abilities))
    
        types = data['types']
        types = list(map(lambda x: x['type']['name'], types))
    
        stats = data['stats']
        stats = list(map(lambda x: x['stat']['name'], stats))
    
        base_stat = data['stats']
        base_stat = list(map(lambda x: x['base_stat'], base_stat))
        return render_template('pokemon.jinja', poke=poke, data=data, abilities=abilities, types=types, stats=stats, base_stat=base_stat)  
    
    return render_template('pokemon.jinja', poke=poke)

@poke_bp.route('/user/<username>')
def user(username):
    user_match = User.query.filter_by(username=username).first()
    if not user_match:
        redirect('/')
    box = user_match.box
    return render_template('collection.jinja', user=user_match, box=box)

@poke_bp.route('/pokemon', methods=['GET', 'POST'])
def collect_card():
    poke = PokemonForm()
    pokemon = user_input[0]
    card = CollectedPokemon(pokemon=pokemon, user_id=current_user.id)
    card.commit()
    return render_template('collection.jinja', poke=poke)

@poke_bp.route('/poke/<pokemon>,<username>', methods=['GET', 'POST'])
def show_card(pokemon, username):
    user_match = User.query.filter_by(username=username).first()
    if not user_match:
        redirect('/')
    box = user_match.box
    req = requests.get(f'https://pokeapi.co/api/v2/pokemon/{pokemon}')
    data = req.json()
    
    
    abilities = data['abilities']
    abilities = list(map(lambda x: x['ability']['name'], abilities))

    types = data['types']
    types = list(map(lambda x: x['type']['name'], types))

    stats = data['stats']
    stats = list(map(lambda x: x['stat']['name'], stats))

    base_stat = data['stats']
    base_stat = list(map(lambda x: x['base_stat'], base_stat))
    return render_template('collection.jinja', user=user_match, box=box, data=data, abilities=abilities, types=types, stats=stats, base_stat=base_stat)

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>PokePicker</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body class="container mt-1">
    {% include 'navbar.jinja' %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
            <li> {{ message }} </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <h1>PokePicker</h1>
    {% if current_user.is_active %}
        <p>Greetings trainer {{ current_user.username }}</p>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>

app/templates/collection.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>{{ self.username }}</h2>
    
    {% for cards in box %}
        
        <a href="{{ url_for('poke.show_card', pokemon=cards.pokemon, username=current_user.username ) }}">{{ cards.pokemon }}</a> <br>
        
    {% endfor %}

    {% if data  %}
    
        <div class="card ml-50" style="width: 18rem;">
            <img src="{{ data['sprites']['front_default'] }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ data['name'] }}</h5>
                    <p class="card-text">Type: {{ data['types'][0]['type']['name'] }} <br>
                                        Abilities: {{ abilities[0] }}, {{ abilities[1] }} <br>
                                        Stats: <br>
                                        {{ stats[0] }}: {{ base_stat[0] }} <br>
                                        {{ stats[1] }}: {{ base_stat[1] }} <br>
                                        {{ stats[2] }}: {{ base_stat[2] }} <br>
                                        {{ stats[3] }}: {{ base_stat[3] }} <br>
                                        {{ stats[4] }}: {{ base_stat[4] }} <br>
                                        {{ stats[5] }}: {{ base_stat[5] }}</p>
                                      
                </div>
            </div>
        
    {% endif %}
    
    
{% endblock %}

app/templates/index.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Welcome to PokePicker</h2>
    
{% endblock %}
</body>
</html>

app/templates/login.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Log In</h2>
    <form action="" method="post">
            {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
        </p> 
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
        </p>
        <p>{{ form.remember_me }}  {{ form.remember_me.label }}</p>
        <p>
            {{ form.submit(class='btn btn-primary') }}
        </p>
    </form>
{% endblock %}

app/templates/navbar.jinja
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">PokePicker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
        {% if current_user.is_anonymous %}
        <a class="nav-link" href="{{ url_for('auth.register') }}">Sign Up</a>
        <a class="nav-link" href="{{ url_for('auth.login') }}">Sign In</a>
        {% else %}
        <a class="nav-link" href="{{ url_for('poke.pick_pokemon') }}">Pokemon</a>
        <a class="nav-link" href="{{ url_for('user.user', username=current_user.username)}}">Profile</a>
        <a class="nav-link" href="{{ url_for('poke.user', username=current_user.username)}}">Collection</a>
        <a class="nav-link" href="{{ url_for('user.post') }}">Post</a>
        <a class="nav-link" href="{{ url_for('auth.log_out') }}">Logout</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

app/templates/pokemon.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Choose your Pokemon</h2>
    <form action="{{ url_for('poke.pick_pokemon') }}" method="post">
            {{ poke.hidden_tag() }}
            <p>
                {{ poke.pokemon.label }} <br>
                {{ poke.pokemon(size=32) }}
            </p>
            <p>
                {{ poke.submit(class='btn btn-primary') }}
            </p> 
            
            {% if data %}  
            <div class="card" style="width: 18rem;">
            <img src="{{ data['sprites']['front_default'] }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ data['name'] }}</h5>
                    <p class="card-text">Type: {{ data['types'][0]['type']['name'] }}<br>
                                        Abilities: {{ abilities[0] }}, {{ abilities[1] }} <br>
                                        Stats: <br>
                                        {{ stats[0] }}: {{ base_stat[0] }} <br>
                                        {{ stats[1] }}: {{ base_stat[1] }} <br>
                                        {{ stats[2] }}: {{ base_stat[2] }} <br>
                                        {{ stats[3] }}: {{ base_stat[3] }} <br>
                                        {{ stats[4] }}: {{ base_stat[4] }} <br>
                                        {{ stats[5] }}: {{ base_stat[5] }}</p>
                    <a href="{{ url_for('poke.collect_card') }}" class="btn btn-primary">Collect</a>
                </div>
            </div>
            {% endif %}
    </form>
{% endblock content %}

app/templates/post.jinja
{% extends "base.jinja" %}


{% block content %}
    <h2>Create Post</h2>
    <form action="" method="post">
            {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br>
            {{ form.title(size=18) }}
        </p> 
        <p>
            {{ form.body.label }}<br>
            {{ form.body(size=64) }}
        </p>
        <p>
            {{ form.submit(class='btn btn-primary') }}
        </p>
    </form>
{% endblock %}

app/templates/register.jinja
{% extends "base.jinja" %}

{% block content %}
    <h2>Register</h2>
    <form action="" method="post">
            {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.first_name.label }}<br>
            {{ form.first_name(size=32) }}
            {% for error in form.first_name.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.last_name.label }}<br>
            {{ form.last_name(size=32) }}
            {% for error in form.last_name.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.confirm_password.label }}<br>
            {{ form.confirm_password(size=32) }}
            {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.submit(class='btn btn-primary') }}
        </p>
    </form>
{% endblock %}

app/templates/trainer.jinja
{% extends "base.jinja" %}

{% block content %}
<h2>{{ user.username }} Trainer Profile</h2>

{% for post in posts %}
    <p>Trainer {{ post.author.username }}: {{ post.body }}</p>
{% endfor %}
{% endblock %}